version: '3.8'

services:
  backend-api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=jdbc:postgresql://tuievolution-postgres:5432/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - tuievolution-postgres
      - tuievolution-mongo

  tuievolution-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  tuievolution-mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  # --- YENİ EKLENEN NGROK SERVİSİ ---
  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    command: "http backend-api:8080" # Routes traffic directly to your Spring Boot container
    depends_on:
      - backend-api

volumes:
  postgres_data: