# Eğer Docker'dan bir adres gelirse onu kullan, gelmezse (IDE'den çalıştırıyorsan) localhost'u kullan
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tuievolution_db}
spring.datasource.username=${DB_USER:tuievolution}
spring.datasource.password=${DB_PASS:tui26*Evolution06}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update