# --- VERİTABANI BAĞLANTISI ---
# Bağlantı ayarları (URL, Username, Password) artık DataSourceConfig.java içinden yönetiliyor.
# Buradan silindiler.

# --- HİBERNATE VE JPA AYARLARI ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- PORT AYARI ---
server.port=${PORT:10000}